# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUnsuccessfulattempttovisittheUserspageasanonadminuser():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_unsuccessfulattempttovisittheUserspageasanonadminuser(self):
    self.driver.get("https://localhost/login.php")
    self.driver.set_window_size(1131, 879)
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("Andy1")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("Andy1")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, "h2")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(3)").click()
  
